version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=./mlruns
    volumes:
      - ./models:/app/models
      - ./mlruns:/app/mlruns
